### ISSUE TITLE
Initialization of OracleEnvironment fails to initialize if Oracle 12c JDBC driver is used

### ISSUE THREAD

**Issue by javornikolov** [dbfit/dbfit#164]
Initialization of OracleEnvironment fails to initialize if Oracle 12c JDBC driver is used.

```
java.lang.Error: java.lang.reflect.InvocationTargetException
    at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.createEnvironmentInstance(DbEnvironmentFactory.java:68)
    at dbfit.api.DbEnvironmentFactory.createEnvironmentInstance(DbEnvironmentFactory.java:102)
    at dbfit.api.DbEnvironmentFactory.newEnvironmentInstance(DbEnvironmentFactory.java:106)
    at dbfit.OracleTest.(OracleTest.java:5)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at java.lang.Class.newInstance(Class.java:374)
    at fit.FixtureClass.newInstance(FixtureClass.java:24)
    at fit.FixtureLoader.instantiateFixture(FixtureLoader.java:62)
    at fit.FixtureLoader.instantiateFirstValidFixtureClass(FixtureLoader.java:84)
    at fit.FixtureLoader.disgraceThenLoad(FixtureLoader.java:44)
    at fit.Fixture.loadFixture(Fixture.java:141)
    at fit.Fixture.getLinkedFixtureWithArgs(Fixture.java:133)
    at fit.Fixture.doTables(Fixture.java:78)
    at fit.FitServer.process(FitServer.java:81)
    at fit.FitServer.run(FitServer.java:56)
    at fit.FitServer.main(FitServer.java:41)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.createEnvironmentInstance(DbEnvironmentFactory.java:65)
    ... 18 more
Caused by: java.lang.Error: Cannot initialise oracle rowset
    at dbfit.environment.OracleEnvironment.(OracleEnvironment.java:203)
    ... 23 more
Caused by: java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleResultSetImpl
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:190)
    at dbfit.environment.OracleEnvironment.(OracleEnvironment.java:199)
    ... 23 more
```

I'll check if helps to switch switching the following to some parent interface/class

``` java
            TypeNormaliserFactory.setNormaliser(
                    Class.forName("oracle.jdbc.driver.OracleResultSetImpl"),
                    new OracleRefNormaliser());
```

**Comment by indianidol** [comment]
This Issue is reproduced in the dbfit-complete-3.2.0 with 
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit 
ojdbc7.jar

![image](https://user-images.githubusercontent.com/7468270/54207632-7df65180-44a8-11e9-8f95-60a43d366fa0.png)
![image](https://user-images.githubusercontent.com/7468270/54208061-45a34300-44a9-11e9-9a20-13952efa7be6.png)
![image](https://user-images.githubusercontent.com/7468270/54208282-97e46400-44a9-11e9-936b-4fe2a43421c7.png)

**Comment by Katze86** [comment]
> 
> 
> This Issue is reproduced in the dbfit-complete-3.2.0 with
> Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit
> ojdbc7.jar
> 
> ![image](https://user-images.githubusercontent.com/7468270/54207632-7df65180-44a8-11e9-8f95-60a43d366fa0.png)
> ![image](https://user-images.githubusercontent.com/7468270/54208061-45a34300-44a9-11e9-9a20-13952efa7be6.png)
> ![image](https://user-images.githubusercontent.com/7468270/54208282-97e46400-44a9-11e9-936b-4fe2a43421c7.png)

Did you solve this problem in DBFit?
