### ISSUE TITLE
Query table doesn't provide good feedback when there is an SQL error

### ISSUE THREAD

**Issue by benilovj** [dbfit/dbfit#34]
![image](https://f.cloud.github.com/assets/23801/236765/87856732-87fc-11e2-8554-1a88fa90ea52.png)

There is STDERR output in this case:

```
 java.sql.SQLException: ORA-00942: table or view does not exist

  at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
  at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
  at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
  at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
  at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
  at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:813)
  at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1049)
  at oracle.jdbc.driver.T4CPreparedStatement.executeMaybeDescribe(T4CPreparedStatement.java:854)
  at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1154)
  at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3370)
  at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3415)
  at dbfit.fixture.Query.getDataTable(Query.java:42)
  at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:78)
  at fit.Fixture.doTable(Fixture.java:154)
  at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:18)
  at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:99)
  at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:87)
  at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:69)
  at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:34)
  at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
  at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:25)
  at fit.Fixture.doTables(Fixture.java:80)
  at fit.FitServer.process(FitServer.java:81)
  at fit.FitServer.run(FitServer.java:56)
  at fit.FitServer.main(FitServer.java:41)
```

**Comment by kenn9j** [comment]
+1 any idea if this has been or could be looked at
