### ISSUE TITLE
SQL Server 2014 - Stored Procedure with OUTPUT-Parameter of type timestamp/rowversion 

### ISSUE THREAD

**Issue by OB4** [dbfit/dbfit#357]
Hallo @javornikolov,  I get an exception with following Stored Procedure:
``` sql
CREATE PROCEDURE [dbo].[Timestamp_P] (@Name NVARCHAR(10),@rvRet rowversion OUTPUT)
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO dbo.TimestampTable (Name) VALUES (@Name);
	SELECT @rvRet = t.rv
	FROM TimestampTable t
	WHERE @Name = t.name;
END
```
Here the test:

```
!|Execute|!-
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TimestampTable]') AND type in (N'U'))
DROP TABLE [dbo].[TimestampTable]
-!|
!|Commit|

!|Execute|Create Table TimestampTable(name varchar(10), rv rowversion)|
!|Insert|TimestampTable|
|name|
|Name1|
!|Commit|

!|Ordered Query|select * from TimestampTable|
|name|rv?|
|Name1|>>rv1|

!|Execute Procedure|Timestamp_P|
|name|rvRet?|
|Name2|>>rv2|
```
```
The Stored Procedure "Timestamp_P throws an exception:
com.microsoft.sqlserver.jdbc.SQLServerException: Operandentypkollision: datetime2 ist inkompatibel mit timestamp
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1522)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1716)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:332)
	at dbfit.fixture.StatementExecution.run(StatementExecution.java:24)
	at dbfit.fixture.DbObjectExecutionFixture.executeStatementAndEvaluateOutputs(DbObjectExecutionFixture.java:184)
	at dbfit.fixture.DbObjectExecutionFixture.runRow(DbObjectExecutionFixture.java:155)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:79)
	at fit.Fixture.doTable(Fixture.java:155)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:18)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:99)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:87)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:69)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:34)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

**Comment by javornikolov** [comment]
What happens if you change the data type from `roweversion` to `timestamp`, `datetime2`?

**Comment by OB4** [comment]
The error occurs on unchanged with timestamp. The type datetime2 I can't use.

**Comment by MMatten** [comment]
I can try helping to resolve this one as I have access to all DB types.

The above stack dump (mentioning datetime2) doesn't match up to the DDL (not mentioning datetime2) given.

@OB4 Can you clarify what you've tried please?

**Comment by OB4** [comment]
Look to  the beginning. There is a Stored Procedure "Timestamp_P" created to test with. Then there is following the test, where Test-table "TimestampTable" is created with a rowversion-column. When you execute the Stored Procedure you get an exception. Maybe the JDBC-Driver don't work correct. Now I use the .net-version of dbfit. There is no problem.

**Comment by MMatten** [comment]
I guess this was missing data type support for TIMESTAMP/ROWVERSION that's been added to FitSharp's version.
