### ISSUE TITLE
Timestamp constant in WHERE clause of Query fixture doesn't work

### ISSUE THREAD

**Issue by z0diak** [dbfit/dbfit#406]
Hi all,

DB: Teradata
Problem: Trying to use Query fixture with query that contains timestamp constant as filter in Where clause. Got Java exception: [Error 3706] [SQLState 42000] Syntax error: Invalid TimeStamp Literal.
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDatabaseSQLException(ErrorFactory.java:308)

**Way to reproduce**
```
|Execute Ddl|CREATE MULTISET TABLE dftest.Td_timestamp (id number, ts timestamp) NO PRIMARY INDEX|

!|Insert|dftest.Td_timestamp|
|id|ts|
|1|2014-09-25 16:26:11|
|2|2014-09-23 16:25:10|

!|Inspect query|SELECT id, ts FROM dftest.Td_timestamp|

!|Query|SELECT id FROM dftest.Td_timestamp|
|id|
|1|
|2|

!|Query|SELECT id, ts FROM dftest.Td_timestamp where id=1|
|id|ts|
|1|2014-09-25 16:26:11|

!|Query|SELECT id, ts FROM dftest.Td_timestamp where ts > TIMESTAMP '2014-01-01 00:00:00'|
|id|ts|
|1|2014-09-25 16:26:11|
|2|2014-09-23 16:25:10|

!|Execute Ddl|DROP TABLE dftest.Td_timestamp|
```

And here is Insert Query output:
```
Inspect query 	SELECT id, ts FROM dftest.Td_timestamp
 id 	 ts
 1 	 2014-09-25 16:26:11.0
 2 	 2014-09-23 16:25:10.0
```

Test goes in following way:
Insert done, first and second Query fixtures shows success, but when it comes to last Query fixture it show exception:
```
java.sql.SQLException: [Teradata Database] [TeraJDBC 15.10.00.05] [Error 3706] [SQLState 42000] Syntax error: Invalid TimeStamp Literal.
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDatabaseSQLException(ErrorFactory.java:308)
	at com.teradata.jdbc.jdbc_4.statemachine.ReceiveInitSubState.action(ReceiveInitSubState.java:109)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementReceiveState.subStateMachine(StatementReceiveState.java:307)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementReceiveState.action(StatementReceiveState.java:196)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementController.runBody(StatementController.java:123)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementController.run(StatementController.java:114)
	at com.teradata.jdbc.jdbc_4.TDStatement.executeStatement(TDStatement.java:386)
etc.
```

Removing centiseconds (.0) or modifying precision doesn't help.
The very same query executed directly from bteq of Teradata SQL Assistant with default settings work fine.

**Workaround**
It works if firstly set up a parameter with value of TIMESTAMP '2014-01-01 00:00:00' and then use this parameter in Query fixture.

**Comment by MMatten** [comment]
To see what's happening. what if you include:

`|set option|bind symbols|false|`

before the last `Query` fixture?

**Comment by z0diak** [comment]
@MMatten included, works fine now. You think it's because of ":" symbols in timestamp literal?

**Comment by MMatten** [comment]
Yes. ":" is used as the parameter prefix in the Teradata adapter. Other adapters use different characters. E.g. SQL Server uses `@`.

I guess we could make the character used to identify parameters to be configurable via a different option.

@javornikolov - any view?

**Comment by javornikolov** [comment]
Yes, Oracle is also using `:` for bind variables which leads to similar issues.
I guess an alternative workaround would be to use to_timestamp with an explicitly specified mask which doesn't contain `:` character.

**Comment by z0diak** [comment]
btw, it will be also good to have warnings\errors in case of unbinded variables in fixture. As far as I understood in my query I has ":00" variable which has no value. It could help to debug tests. 
It's a new feature\enhancement of course
