### ISSUE TITLE
Insert Fixture failed : Oracle RAW / LONG RAW / BINARY / VARBINARY column type

### ISSUE THREAD

**Issue by Auguronomics** [dbfit/dbfit#407]
Hi, 
I would like submit an issue, I bring my solution a the end of this article.
My issue is : 
I can't use Insert fixture to insert data row in table cause a Raw column type is not supported

!|Execute|!- CREATE TABLE MyTable ( ID INTEGER, LABEL NVARCHAR2(15), GUID RAW(16) DEFAULT SYS_GUID() NOT NULL) -!|

!|Insert|MyTable|
|ID     |LABEL  |
|1      |A      |

!|Execute|DROP TABLE MyTable|

Failed :java.lang.UnsupportedOperationException: Type RAW is not supported
	at dbfit.environment.OracleEnvironment.getSqlType(OracleEnvironment.java:429)
	at dbfit.environment.OracleEnvironment.makeSingleParam(OracleEnvironment.java:334)
	at dbfit.environment.OracleEnvironment.makeSingleParam(OracleEnvironment.java:317)
	at dbfit.environment.OracleEnvironment.addSingleParam(OracleEnvironment.java:307)
	at dbfit.environment.OracleEnvironment.readIntoParams(OracleEnvironment.java:351)
	at dbfit.environment.OracleEnvironment.getAllColumns(OracleEnvironment.java:302)
	at dbfit.api.DbTable.(DbTable.java:24)
	at dbfit.fixture.Insert.getTargetDbObject(Insert.java:32)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:61)
	at fit.Fixture.doTable(Fixture.java:155)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:18)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:99)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:87)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:69)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:34)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)

But when I modify OracleEnvironment.java 
    // List interface has sequential search, so using list instead of array to
    // map types
    private static List<String> stringTypes = Arrays.asList(new String[] {
            "VARCHAR", "VARCHAR2", "NVARCHAR2", "CHAR", "NCHAR", "CLOB",
            "NCLOB", "ROWID", "BOOLEAN", "RAW"
        });
it works fine, I know RAW and (VAR) Binary types aren't yet supported, but Insert fixture to insert  data in table with RAW's column with default value or nullable  could be use like this sample.

Thank you for your attention.

Damien Maresma

**Comment by MMatten** [comment]
What happens if you try to insert data into the RAW column in the Insert fixture?

What happens when you try to test the contents of a RAW column using a Query fixture?

**Comment by MMatten** [comment]
> but Insert fixture to insert data in table with RAW's column with default value or nullable could be use like this sample.

You're right. It's a work-around but I think it's unlikely we'd want to put this into the actual DbFit code base like that. Proper RAW and BLOB support would be better and I think hex display and input formats would work well, as mentioned by @javornikolov.

**Comment by javornikolov** [comment]
related to #405

**Comment by javornikolov** [comment]
Maybe as a start we can add just enough mappings for the `RAW` data type so that `getSqlType` and `getJavaClass` aren't failing.
As soon as such columns are not explicitly used in the test tables - I guess we could postpone the underlying implementation for full RAW support.

The Java types/constants related to `RAW` I think should be: `java.sql.Types.BINARY`, `byte[]`, `oracle.sql.RAW`.

**Comment by MMatten** [comment]
> `java.sql.Types.BINARY`

Or perhaps `java.sql.Types.VARBINARY`?

**Comment by MMatten** [comment]
There could be some reuse for #386 too.

**Comment by javornikolov** [comment]
> java.sql.Types.BINARY
> 
> Or perhaps java.sql.Types.VARBINARY?

Or... LONGVARBINARY? http://docs.oracle.com/cd/E11882_01/java.112/e16548/datacc.htm
