### ISSUE TITLE
Query Fixture: Can not store cell value in parameter

### ISSUE THREAD

**Issue by z0diak** [dbfit/dbfit#409]
Hi all,
Here is the problem:
|Ordered Query| select current_date as cur_date, current_date-1 as prev_date| 
|cur_date|prev_date|
|>>cur_date|>>prev_date|

|Query| select current_date as cur_date, current_date-1 as prev_date| 
|cur_date|prev_date|
|>>cur_date2|>>prev_date2|

First fixture work fine, second one gives exception:
```
java.text.ParseException: Unparseable date: ">>cur_date2"
	at java.text.DateFormat.parse(DateFormat.java:357)
	at dbfit.util.SqlDateParseDelegate.parse(SqlDateParseDelegate.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at fit.TypeAdapter$DelegateClassAdapter.parse(TypeAdapter.java:354)
	at dbfit.util.ParseHelper.parse(ParseHelper.java:71)
	at dbfit.fixture.RowSetFixture$CurrentDataRowTypeAdapter.parse(RowSetFixture.java:49)
	at dbfit.fixture.RowSetFixture.findMatchingRow(RowSetFixture.java:123)
	at dbfit.fixture.RowSetFixture.doRow(RowSetFixture.java:107)
	at fit.Fixture.doRows(Fixture.java:162)
	at fit.ColumnFixture.doRows(ColumnFixture.java:19)
	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:93)
	at fit.Fixture.doTable(Fixture.java:156)
	at fit.Fixture.interpretFollowingTables(Fixture.java:121)
	at fit.Fixture.interpretTables(Fixture.java:107)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

Database: Teradata 14.10

**Comment by MMatten** [comment]
And with:

|Query| select current_date as cur_date, current_date-1 as prev_date| 
|cur_date?|prev_date?|
|>>cur_date2|>>prev_date2|

)

**Comment by z0diak** [comment]
@MMatten woah, didn't know that. Thanks)

**Comment by MMatten** [comment]
Might be better in future to post queries/issues on the Google forum first.
