### ISSUE TITLE
Could not find fixture: Query.

### ISSUE THREAD

**Issue by satybald** [dbfit/dbfit#449]
I've installed DBFit v3.2.0, after unziping it from a local dir and running a query:
```
|Import|
|dbfit.fixtures|

|Query|!- select case when count(*) > 100000 then true else false end "ASSERT" from webclient_report where dt = '2015-10-01' -!|
|ASSERT|
|True|
```

I have an output:
```
dbfit.HiveTest
 Could not find fixture: dbfit.HiveTest.

Connect
 Could not find fixture: Connect.	jdbc:hive2:/URL
.DWHTests.SetUp

Import
dbfit.fixtures

Query
 Could not find fixture: Query.	select case when count(*) > 100000 then true else false end "ASSERT" from webclient_report where dt = '2015-10-01'
ASSERT
True
```

What might be the reason of such behaviour?

**Comment by MMatten** [comment]
Have you read the manual? :smile: 

http://dbfit.github.io/dbfit/docs/index.html

What's your `!path` set to?

Are you using Flow or Standalone modes?

If Standalone mode try: -

```
|Import|
|dbfit.fixture|
```

**Comment by satybald** [comment]
Yea, I did. I didn't get what this phrase referred to:
Replace the contents of the big textbox with the following:

Where to find this "big textbox"? I put the path declaration into SetUp and test pages.

**Comment by satybald** [comment]
>>What's your !path set to?
How would be possible to find what's path bind to?

**Comment by satybald** [comment]
I'm running in Flow mode. I've inserted a path to the main page of the suite. Not it shows the classpath:

```
classpath: lib/*.jar
dbfit.HiveTest
 Could not find fixture: dbfit.HiveTest.

Connect
 Could not find fixture: Connect.	jdbc:hive2://URL
```

**Comment by javornikolov** [comment]
Hi @satybald - you can see the list of databases supported by and bundled with DbFit [here](http://dbfit.github.io/dbfit/docs/getting-started.html). There is no `HiveTest` in the list so far. You can develop/add custom database adapters too - but if you haven't done that, DbFit will not know about `dbfit.HiveTest`.

**Comment by krishabh85** [comment]
I want to use standalone mode and flow mode in the same suite but it shows error such as "Ambiguity between: fixture dbfit.fixture.ExecuteProcedure AND executeProcedure()".
This is because standalone mode is getting executed and then flow mode.
When I changed the names so that flow mode is executed first and then stand alone mode, it starts working.
Can, anybody tell me how to close standalone mode so that flow mode can be started in a suite.

**Comment by MMatten** [comment]
|Export|
|dbfit.fixtures|

After your standalone mode tests. Try that.

**Comment by krishabh85** [comment]
Thanks @MMatten 
!|dbfit.util.Export|
|dbfit.fixture|
  worked for me.
While I ran a suite, it is executed all correct but still a standard error is occuring, can you please tell the solution
Standard Error:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at fit.TypeAdapter$DelegateClassAdapter.parse(TypeAdapter.java:354)
	at dbfit.util.ParseHelper.parse(ParseHelper.java:71)
	at dbfit.fixture.RowSetFixture$CurrentDataRowTypeAdapter.parse(RowSetFixture.java:49)
	at fit.Fixture$CellComparator.parseCell(Fixture.java:395)
	at fit.Fixture$CellComparator.compareCellToResult(Fixture.java:375)
	at fit.Fixture$CellComparator.access$100(Fixture.java:360)
	at fit.Fixture.compareCellToResult(Fixture.java:302)
	at fit.Fixture.check(Fixture.java:298)
	at fit.ColumnFixture.check(ColumnFixture.java:54)
	at fit.Binding$QueryBinding.doCell(Binding.java:218)
	at dbfit.util.SymbolAccessQueryBinding.doCell(SymbolAccessQueryBinding.java:38)
	at fit.ColumnFixture.doCell(ColumnFixture.java:40)
	at fit.Fixture.doCells(Fixture.java:174)
	at fit.Fixture.doRow(Fixture.java:168)
	at fit.ColumnFixture.doRow(ColumnFixture.java:27)
	at dbfit.fixture.RowSetFixture.doRow(RowSetFixture.java:109)
	at fit.Fixture.doRows(Fixture.java:162)
	at fit.ColumnFixture.doRows(ColumnFixture.java:19)
	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:93)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
Caused by: java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:470)
	at java.math.BigDecimal.<init>(BigDecimal.java:739)
	at dbfit.util.BigDecimalParseDelegate.parse(BigDecimalParseDelegate.java:7)
	... 35 more
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at fit.TypeAdapter$DelegateClassAdapter.parse(TypeAdapter.java:354)
	at dbfit.util.ParseHelper.parse(ParseHelper.java:71)
	at dbfit.fixture.RowSetFixture$CurrentDataRowTypeAdapter.parse(RowSetFixture.java:49)
	at fit.Fixture$CellComparator.parseCell(Fixture.java:395)
	at fit.Fixture$CellComparator.compareCellToResult(Fixture.java:375)
	at fit.Fixture$CellComparator.access$100(Fixture.java:360)
	at fit.Fixture.compareCellToResult(Fixture.java:302)
	at fit.Fixture.check(Fixture.java:298)
	at fit.ColumnFixture.check(ColumnFixture.java:54)
	at fit.Binding$QueryBinding.doCell(Binding.java:218)
	at dbfit.util.SymbolAccessQueryBinding.doCell(SymbolAccessQueryBinding.java:38)
	at fit.ColumnFixture.doCell(ColumnFixture.java:40)
	at fit.Fixture.doCells(Fixture.java:174)
	at fit.Fixture.doRow(Fixture.java:168)
	at fit.ColumnFixture.doRow(ColumnFixture.java:27)
	at dbfit.fixture.RowSetFixture.doRow(RowSetFixture.java:109)
	at fit.Fixture.doRows(Fixture.java:162)
	at fit.ColumnFixture.doRows(ColumnFixture.java:19)
	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:93)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
Caused by: java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:470)
	at java.math.BigDecimal.<init>(BigDecimal.java:739)
	at dbfit.util.BigDecimalParseDelegate.parse(BigDecimalParseDelegate.java:7)
	... 35 more
