### ISSUE TITLE
Execute Procedure Expect Exception fails for procedures with no parameters

### ISSUE THREAD

**Issue by javornikolov** [dbfit/dbfit#490]
The problem has been reported on the mailing list. Stack trace of a failing example as following;

```
!| Execute Procedure Expect Exception| DBFIT_delete_test_proc |
```

```
com.microsoft.sqlserver.jdbc.SQLServerException: Hard deletes of the dbo.test_table table prohibited.  Set deletedsw=1 instead.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:332)
	at dbfit.fixture.StatementExecution.run(StatementExecution.java:24)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:66)
	at fit.Fixture.doTable(Fixture.java:155)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:18)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:99)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:87)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:69)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:34)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

Looks like in `DbObjectExecutionFixture.doRows` we have separate processing of `no-args` and `with-args` cases where the former doesn't properly handle expected exceptions.

**Comment by MMatten** [comment]
@javornikolov I'll pick this one up next.

**Comment by javornikolov** [comment]
Cool :+1: Thank you!

**Comment by MMatten** [comment]
After having done some work on this, something occurred to me; should we look to handle the exception of "the actual procedure doesn't actually exist" in a specific way, or just allow this to not report an exception to the test results?

**Comment by javornikolov** [comment]
That's a very good question. I think we don't have a specific test to illustrate what happens in such case.

My intuition is that `expecting exception` should only pass if the stored proc call succeeded but it has raised an error.

**Comment by javornikolov** [comment]
Anyway - perhaps we should tackle the case with non-existing sp in separate issue.

**Comment by MMatten** [comment]
@javornikolov I'll resume work on resolving this next.

**Comment by javornikolov** [comment]
> @javornikolov I'll resume work on resolving this next.

Great. When we're done with that I guess we can issue a new release.

**Comment by javornikolov** [comment]
@MMatten is there anything which should be done about this issue?

**Comment by MMatten** [comment]
@javornikolov - indeed there should. I can do some work on it towards the end of this week so we can roll it into the next release. It’s been hanging around for a very long time.

**Comment by javornikolov** [comment]
I think we can roll out 4.0.0 without it. And we can have 4.0.1 or 4.1.0 soon after that.

**Comment by MMatten** [comment]
OK. That sounds good to me.
