### ISSUE TITLE
NullPointerException happens when connection to a remote Oracle database

### ISSUE THREAD

**Issue by josueboix** [dbfit/dbfit#493]
Hello,

I'm struggling to make Dbfit work using an Oracle database in a remote server. For that connection I use a tunnel using SSH, then I run simple verification using SELECT queries. 

First of all, I encounter a problem using the JDBC driver, the issue is describer here:
https://github.com/dbfit/dbfit/issues/164

I fixed this problem using 11.2 driver instead of 12.1, but know I'm having another problem which I describe as follows:

When I click Test, I get several NullPointerException, the test looks something like the following:

```
!define dburl {localhost}
!define dbport {1521}
!define dbname {***}
!define dbuser {***}
!define dbpassword {***}

!|dbfit.OracleTest |
!|Connect |${dburl}:${dbport} |${dbuser} |${dbpassword} |orcl |

|set option|bind symbols|false|

|Query |SELECT status FROM *** WHERE name = '1234' |
|field1 |field2 |
|value1 |value2 |
```

But the result I get is quite shocking, I get the following error repeated 6 times:

null

```
java.lang.NullPointerException
	at dbfit.fixture.RowSetFixture.addSurplusRows(RowSetFixture.java:142)
	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:94)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

and then:

```
Query 	SELECT status FROM *** WHERE name = '1234'
field1 field2

java.lang.Exception: Unknown column billingengine
	at dbfit.fixture.RowSetFixture.findColumn(RowSetFixture.java:63)
	at dbfit.fixture.RowSetFixture.bind(RowSetFixture.java:74)
	at fit.ColumnFixture.doRows(ColumnFixture.java:18)
	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:93)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)

	
valu1 	value2

java.lang.NullPointerException
	at fit.ColumnFixture.doCell(ColumnFixture.java:40)
	at fit.Fixture.doCells(Fixture.java:174)
	at fit.Fixture.doRow(Fixture.java:168)
	at fit.ColumnFixture.doRow(ColumnFixture.java:27)
	at dbfit.fixture.RowSetFixture.doRow(RowSetFixture.java:109)
	at fit.Fixture.doRows(Fixture.java:162)
	at fit.ColumnFixture.doRows(ColumnFixture.java:19)
	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:93)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

Any idea what is happening?

Thanks in advance!

**Comment by javornikolov** [comment]
The following test command is not quite right:
```
|Query |SELECT status FROM *** WHERE name = '1234' |
|field1 |field2 |
|value1 |value2 |
```

The query has only `status` column - while you're looking for `field1` and `field2`.

**Comment by josueboix** [comment]
Sorry for wasting your time, I copied it wrong.

I managed to fix the error, it was caused by a problem with the tunnel.

**Comment by jairaj15** [comment]
Hi ,
I am trying to use DBFit for automating queries. Now when we try comparing large data set I have tried the following query but results show yellow indicating neither error nor pass:
**Query:**
!define q1 {SELECT A.SALES_ID as SALES_ID,
                 'q1' as source
from  (select A.SALES_MANIFEST_ID from R_SALES_MANIFEST_H A, X_SALESSRCLNK B , R_SALES_METADATA_H C
where nvl(A.SOURCE_ROW_ID,0) = nvl(B.SALESSRCLNK_PK,0) and
nvl(C.SOURCE_ROW_ID,0) = nvl(B.SALESSRCLNK_SALESDATAFK,0))}

!define q2 {SELECT SALES_MANIFEST_ID as SALES_MANIFEST_ID,
                 'q2' as source                 
                      FROM (select SALES_MANIFEST_ID from R_SALES_MANIFEST_METADATA_L)}

|query          |((${q1} MINUS ${q2})) UNION ((${q2} MINUS ${q1}))|
|SALES_MANIFEST_ID|SALES_MANIFEST_ID             |source             |

Compare Store Queries though works well for small data set would like some help on large data set.

**Comment by javornikolov** [comment]
@jairaj15, that's off-topic (look at the title of the issue here). Hints for working with relatively large data sets you may see at: http://dbfit.github.io/dbfit/docs/reference.html#compare-stored-queries
