### ISSUE TITLE
We have found that NVARCHAR(MAX) is not supported in the latest DBFit version

### ISSUE THREAD

**Issue by ErinKozak** [dbfit/dbfit#508]
We have recently upgraded our DBFit to the latest version (it has been years...).  But now a large portion of tests are not working because it does not like NVARCHAR(MAX) as an out parameter.  Any plans on fixing this or any work-arounds?

We now get the error:

System.InvalidOperationException: String[4]: the Size property has an invalid size of 0.
   at System.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   at System.Data.SqlClient.SqlCommand.SetUpRPCParameters(_SqlRPC rpc, Int32 startCount, Boolean inSchema, SqlParameterCollection parameters)
   at System.Data.SqlClient.SqlCommand.BuildRPC(Boolean inSchema, SqlParameterCollection parameters, _SqlRPC& rpc)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at dbfit.fixture.ExecuteProcedure.Execute()
   at fit.ColumnFixture.DoRow(Parse row)

**Comment by javornikolov** [comment]
@ErinKozak, from the error message I can see you're using the .NET version of dbfit (fitSharp) which is quite old. Some discussion on that matter here: https://groups.google.com/d/msg/dbfit/PC_bRBfPm_I/7X1EPyczcosJ.

Could you switch to the Java version?

**Comment by ErinKozak** [comment]
I changed my TEST_RUNNER to fit.FitServer, but i'm not sure what my path should be changed to though?

**Comment by javornikolov** [comment]
You need to install Java (ideally latest version). Environment variables which are good to set are: `JAVA_HOME` - path where java was installed; `PATH` should include `%JAVA_HOME%\bin`. You'll also need to install SQL Server JDBC driver: http://dbfit.github.io/dbfit/docs/database-specific-information.html#microsoft-sql-server

Starting dbfit is via `startFitnesse.bat` script: http://dbfit.github.io/dbfit/docs/getting-started.html

**Comment by ErinKozak** [comment]
I have used DBFit before - my current path was !path FitSharp\dbfit.sqlserver.dll and !define TEST_RUNNER {fitsharp\Runner.exe}   What do i need to change once i download the JDBC driver?

**Comment by javornikolov** [comment]
You can remove these two defines and add `!path lib/*.jar` instead: http://dbfit.github.io/dbfit/docs/getting-started.html.

**Comment by ErinKozak** [comment]
ok got that.  where do i put the JDBC driver then?

**Comment by javornikolov** [comment]
dbfit's `lib` folder (next to other `.jar` files there). Some MS SQL Server specific notes are described here: http://dbfit.github.io/dbfit/docs/database-specific-information.html
