### ISSUE TITLE
Java error. Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by elephant33** [dbfit/dbfit#509]
Hi, 
I'm trying to set up dbfit to run on my localhost and connect to my redshift cluster. 
I've updated my java to (build 1.8.0_101-b13) but still does not work... can someone help please?

java.lang.UnsupportedClassVersionError: dbfit/PostgresTest : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:276)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:169)
	at fit.FixtureLoader.loadFixtureClass(FixtureLoader.java:67)
	at fit.FixtureLoader.instantiateFixture(FixtureLoader.java:60)
	at fit.FixtureLoader.instantiateFirstValidFixtureClass(FixtureLoader.java:84)
	at fit.FixtureLoader.disgraceThenLoad(FixtureLoader.java:44)
	at fit.Fixture.loadFixture(Fixture.java:142)
	at fit.Fixture.getLinkedFixtureWithArgs(Fixture.java:134)
	at fit.Fixture.doTables(Fixture.java:79)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)

**Comment by javornikolov** [comment]
Can you double check that you have the correct environment set in the shell where you're starting DbFit (FitNesse) server - in particular `JAVA_HOME` and `PATH`?

E.g. from the console/command prompt - what's the output of:
`java -version`

**Comment by javornikolov** [comment]
Maybe where you start your FitNesse it's still using other JAVA_HOME or PATH. You can edit `startFitnesse.bat` and print or set the environments settings there.

**Comment by elephant33** [comment]
Hi, Thanks for your help its working now. 
I went back to an older version of jre which I had (jre1.8.0_72). Made sure that the JAVA_HOME environment variable was set to that as well. Works now. Thank you

**Comment by resh03** [comment]
Hi, I'm facing a similar issue. I have a fitnesse project which works perfectly fine in windows environment but when i execute the same in Linux it gives me error unsupported major minor version 52.
(Which means that the compilation is in JAVA 8 but the executing environment is lower.)
Though my linux box has a default java of version 1.6 (which I cant change), we also have java 8 installed. So i'm running my fitnesse jar explicitly from the java 8 path 
/{linux_path}/oracle-jdk/1.8.0.45/linux_x64/jre/bin/java -jar fitnesse-standalone.jar -p 9090
Yet the same issue while running the test. 
Please help. what am i missing?

**Comment by MMatten** [comment]
Does setting the JAVA_HOME environment variable to the parent of the bin directory help?

Sent from my iPhone

On 5 Apr 2018, at 12:14, resh03 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I'm facing a similar issue. I have a fitnesse project which works perfectly fine in windows environment but when i execute the same in Linux it gives me error unsupported major minor version 52.
(Which means that the compilation is in JAVA 8 but the executing environment is lower.)
Though my linux box has a default java of version 1.6 (which I cant change), we also have java 8 installed. So i'm running my fitnesse jar explicitly from the java 8 path
/{linux_path}/oracle-jdk/1.8.0.45/linux_x64/jre/bin/java -jar fitnesse-standalone.jar -p 9090
Yet the same issue while running the test.
Please help. what am i missing?

**Comment by resh03** [comment]
Well kind of tried that too... we have a env.sh file which sets
java_home.M2_home variables etc. But same error....

**Comment by MMatten** [comment]
Try removing the other java version from the path too.
