### ISSUE TITLE
Data diff for large data sets do not show any results

### ISSUE THREAD

**Issue by jairaj15** [dbfit/dbfit#521]
Hi ,
 I am trying to use DBFit for automating queries. Now when we try comparing large data set I have tried the following query but results show yellow indicating neither error nor pass:
Query:
 !define q1 {SELECT A.SALES_ID as SALES_ID,
 'q1' as source
 from (select A.SALES_MANIFEST_ID from R_SALES_MANIFEST_H A, X_SALESSRCLNK B , R_SALES_METADATA_H C
 where nvl(A.SOURCE_ROW_ID,0) = nvl(B.SALESSRCLNK_PK,0) and
 nvl(C.SOURCE_ROW_ID,0) = nvl(B.SALESSRCLNK_SALESDATAFK,0))}

!define q2 {SELECT SALES_MANIFEST_ID as SALES_MANIFEST_ID,
 'q2' as source
 FROM (select SALES_MANIFEST_ID from R_SALES_MANIFEST_METADATA_L)}

|query |((${q1} MINUS ${q2})) UNION ((${q2} MINUS ${q1}))|
 |SALES_MANIFEST_ID|SALES_MANIFEST_ID |source |

Compare Store Queries though works well for small data set would like some help on large data set.

**Comment by javornikolov** [comment]
Please take a look at: http://dbfit.github.io/dbfit/docs/reference.html#compare-stored-queries (sorting of stored queries and hiding matching rows usually helps for larger data sets).

**Comment by jairaj15** [comment]
Hi,
I have tried using comparing as you mentioned using following fixture 
|compare stored queries hide matching rows| 
but for data sets too large then I encounter:
java.lang.OutOfMemoryError: Java heap space
	at java.util.regex.Pattern$CharProperty.complement(Pattern.java:3687)
	at java.util.regex.Pattern.clazz(Pattern.java:2517)
	at java.util.regex.Pattern.sequence(Pattern.java:2030)
	at java.util.regex.Pattern.expr(Pattern.java:1964)
	at java.util.regex.Pattern.compile(Pattern.java:1665)
	at java.util.regex.Pattern.(Pattern.java:1337)
	at java.util.regex.Pattern.compile(Pattern.java:1022)
	at java.lang.String.replaceAll(String.java:2162)
	at dbfit.util.NameNormaliser.replaceIllegalCharacters(NameNormaliser.java:14)
	at dbfit.util.NameNormaliser.normaliseName(NameNormaliser.java:22)
	at dbfit.util.DataRow.addValue(DataRow.java:30)
	at dbfit.util.DataRow.(DataRow.java:18)
	at dbfit.util.DataTable.init(DataTable.java:36)
	at dbfit.util.DataTable.(DataTable.java:17)
	at dbfit.fixture.StoreQuery.doTable(StoreQuery.java:45)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)

**Comment by javornikolov** [comment]
You can review FitNesse forums/docs about how to configure your Java VM memory settings with larger heap size: http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.CustomizingTestExecution
(Most likely you just need to tweak COMMAND_PATTERN by adding -Xms ... -Xmx ... options to the `java` call) pattern.
