### ISSUE TITLE
Dev VM: error creating LVM physical volume

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#533]
Error creating LVM physical volume:

```
==> default:     ================================================================================
==> default:     Error executing action `create` on resource 'lvm_physical_volume[/dev/sdb]'
==> default:     ================================================================================
==> default:     
==> default:     ArgumentError
==> default:     -------------
==> default:     Unable to load lvm attributes [lvs.yaml] for version [2.02.166(2)]. The version/object may not be supported or you may need to upgrade the di-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-attrib-0.0.27/lib/lvm/attributes/2.02.166(2)/lvs.yaml]
==> default:     
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_physical_volume.rb:47:in `new'
==> default:     /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_physical_volume.rb:47:in `action_create'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/dbfit_test/recipes/diskspace.rb
==> default:     
==> default:       1: lvm_physical_volume '/dev/sdb' do
==> default:       2:   action :create
==> default:       3: end
==> default:       4: 
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/dbfit_test/recipes/diskspace.rb:1:in `from_file'
==> default:     
==> default:     lvm_physical_volume("/dev/sdb") do
==> default:       provider Chef::Provider::LvmPhysicalVolume
==> default:       action [:create]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :lvm_physical_volume
==> default:       cookbook_name "dbfit_test"
==> default:       recipe_name "diskspace"
==> default:     end
```

**Comment by MMatten** [comment]
The CentOS vagrant image has been updated on the HasiCorp vendor.

**Comment by javornikolov** [comment]
Hmm. What's the output of `pvs`, `vgs`, `lvs`, `ls -l /dev/sd*`?

**Comment by javornikolov** [comment]
@MMatten, could you try with PR #534. The newer `lvm` cookbook has newer version of `di-ruby-lvm-attrib` which is likely to resolve our issue.
