### ISSUE TITLE
DBFit For Oracle HelloWorld

### ISSUE THREAD

**Issue by lriffel** [dbfit/dbfit#536]
I am new to FitNesse and am very interested in seeing it in action, however, I have been unable to get even the HelloWord to work.  The current error it is giving me is "Could not find fixture: Connect."  I'll try list everything I can about the setup so hopefully someone can spot the issue.

- The download is dbfit-complete-3.2.0.zip
- I am running this on Windows 10 x64.
- I extracted the files to c:\fitnesse\.
- I copied all the odbc*.jar files from my oracle home to c:\fitnesse\lib\.
- In startFitnesse.bat I changed java to "C:\Program Files\Java\jre1.8.0_112\bin\java".
- In startFitnesse.bat I added lib\dbfit-oracle-3.2.0.jar;lib\odbc6.jar; to the start of the -cp quoted value.
- Running startFitnesse.bat has the following output:
```
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at .\FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Starting FitNesse on port: 8085
```

- I've created numerous tests trying to get one that would work.  Here is one that seems to get further than others.

```
!path lib\*.jar
!|Import|dbfit.OracleTest|
!|Connect|atappdb2:1535/oadev1|lr|lr|
!|Query| select 'test' as x from dual||x||test|
```

- In the properties I changed the page type to "Test".
- Clicking Test shows the following:
```
classpath: lib\*.jar
Import	dbfit.OracleTest
Connect
 Could not find fixture: Connect.	atappdb2:1535/oadev1	lr	lr
Query
 Could not find fixture: Query.	select 'test' as x from dual		x		test
```
- I've tried many other variations including this one:

```
!define COMMAND_PATTERN {%m %p}
!define TEST_RUNNER {fitsharp\RunnerW.exe}
!define PATH_SEPARATOR {;}
!path fitsharp\*.dll
| Connect | atappdb2:1535/oadev1 | lr| lr|
| Query | select 'test' as x from dual |
| x |
| test |
```

- This one gives this output:

```
Could not complete testing: java.lang.Exception: FitClient: communication socket was not received on time.
```

Please let me know if you need more information or spot something I am doing incorrectly.

**Comment by javornikolov** [comment]
Hi @lriffel, just try the following:

```
!path lib/*.jar

!|dbfit.OracleTest|

!|Connect|atappdb2:1535/oadev1|lr|lr|

!|Query| select 'test' as x from dual|
|x|
|test|
```

You don't need to modify the batch file for odbc6.jar (all lib/*.jar files are added to the classpath `!path lib/*.jar`), you shouldn't modify TEST_RUNNER. You don't need to do `import` (at least for the default flow mode). **Having a blank line between the separate commands is often important**.

You may also look at the docs: http://dbfit.github.io/dbfit/docs/getting-started.html

**Comment by lriffel** [comment]
I had something similar to that at one time, but I've been through a lot of iterations and thought I was a bit closer with what I had.  When I remove odbc6.jar from being in the batch file and change the text to what you provided, I still get the "Could not find fixture: Connect", but now I also get a java error as follows:

`java.lang.Error: java.lang.reflect.InvocationTargetException
	at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.createEnvironmentInstance(DbEnvironmentFactory.java:68)
	at dbfit.api.DbEnvironmentFactory.createEnvironmentInstance(DbEnvironmentFactory.java:102)
	at dbfit.api.DbEnvironmentFactory.newEnvironmentInstance(DbEnvironmentFactory.java:106)
	at dbfit.OracleTest.(OracleTest.java:5)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at fit.FixtureClass.newInstance(FixtureClass.java:24)
	at fit.FixtureLoader.instantiateFixture(FixtureLoader.java:62)
	at fit.FixtureLoader.instantiateFirstValidFixtureClass(FixtureLoader.java:84)
	at fit.FixtureLoader.disgraceThenLoad(FixtureLoader.java:44)
	at fit.Fixture.loadFixture(Fixture.java:142)
	at fit.Fixture.getLinkedFixtureWithArgs(Fixture.java:134)
	at fit.Fixture.doTables(Fixture.java:79)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.createEnvironmentInstance(DbEnvironmentFactory.java:65)
	... 18 more
Caused by: java.lang.Error: Cannot initialise oracle rowset
	at dbfit.environment.OracleEnvironment.(OracleEnvironment.java:236)
	... 23 more
Caused by: java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleResultSetImpl
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at dbfit.environment.OracleEnvironment.(OracleEnvironment.java:232)
	... 23 more`

**Comment by javornikolov** [comment]
I have some doubts about `!path lib/*.jar` on Windows - possibly the slash should be `!path lib\*.jar` (the assumption has been that / should work on all platforms but I'm not quite sure).

I assume you're using ojdbc6.jar version 11.2? (Version 12 is not supported yet).

**Comment by lriffel** [comment]
Yes, I had thought about the slash too, but hadn't tried it on your code.  I tried it now and it had no effect.  Yes, I put the odbc6.jar file in lib/.  But your statement got me thinking.  I copied the odbc6.jar from a 12c home rather than an 11g home.  I went to an 11g home and copied odbc5.jar and odbc6.jar from there and now Hello World works!  Thanks so much.

**Comment by javornikolov** [comment]
You're welcome ;-) Don't copy both odbc5.jar and odbc6.jar - should be odbc6.jar only.

**Comment by lriffel** [comment]
True, works without the odbc5.jar.  It also works without the blank lines between commands.

**Comment by krishabh85** [comment]
@lriffel Can you please give the link of dbfit-oracle-3.2.0.jar. I have searched it madly but didn't get the link to download. It would be wonderful if you can help me out.
Thanks.

**Comment by MMatten** [comment]
Please use the support forum on google groups.
