### ISSUE TITLE
Dev VM provisioning failure (lvm pvcreate /dev/sdb)

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#542]
I'm guessing this is because the CentOS image has been updated yet again and breaks the provisioning.

```
==> default:     ================================================================================
==> default:     Error executing action `create` on resource 'lvm_physical_volume[/dev/sdb]'
==> default:     ================================================================================
==> default:     
==> default:     LVM::External::ExternalFailure
==> default:     ------------------------------
==> default:     Fatal error, `/sbin/lvm pvcreate /dev/sdb ` returned 5 with 'Device /dev/sdb not found (or ignored by filtering).'
==> default:     
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_physical_volume.rb:51:in `action_create'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/dbfit_test/recipes/diskspace.rb
==> default:     
==> default:       1: lvm_physical_volume '/dev/sdb' do
==> default:       2:   action :create
==> default:       3: end
==> default:       4: 
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/dbfit_test/recipes/diskspace.rb:1:in `from_file'
==> default:     
==> default:     lvm_physical_volume("/dev/sdb") do
==> default:       provider Chef::Provider::LvmPhysicalVolume
==> default:       action [:create]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :lvm_physical_volume
==> default:       cookbook_name "dbfit_test"
==> default:       recipe_name "diskspace"
==> default:     end
==> default:     
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux
==> default:     
==> default: [2017-02-08T10:27:41+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2017-02-08T10:27:41+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-02-08T10:27:41+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 9 resources updated in 01 minutes 02 seconds
==> default: [2017-02-08T10:27:41+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-02-08T10:27:41+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-02-08T10:27:41+00:00] ERROR: lvm_physical_volume[/dev/sdb] (dbfit_test::diskspace line 1) had an error: LVM::External::ExternalFailure: Fatal error, `/sbin/lvm pvcreate /dev/sdb ` returned 5 with 'Device /dev/sdb not found (or ignored by filtering).'
==> default: [2017-02-08T10:27:41+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by MMatten** [comment]
Logging into the guest I can see: -

```
[vagrant@dbfitvm ~]$ sudo lvm pvs
  PV         VG         Fmt  Attr PSize  PFree
  /dev/sda3  VolGroup00 lvm2 a--  38.97g    0 
[vagrant@dbfitvm ~]$ sudo lvm lvs
  LV       VG         Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  LogVol00 VolGroup00 -wi-ao---- 37.47g                                                    
  LogVol01 VolGroup00 -wi-ao----  1.50g                                                    
[vagrant@dbfitvm ~]$ sudo lvm vgs
  VG         #PV #LV #SN Attr   VSize  VFree
  VolGroup00   1   2   0 wz--n- 38.97g    0 
```

**Comment by javornikolov** [comment]
```
ls -l /dev/sd* /dev/hd*
```

**Comment by javornikolov** [comment]
Possibly related: #421

**Comment by MMatten** [comment]
Re `ls -l /dev/sd* /dev/hd*` we have: -

```
brw-rw----. 1 root disk 8, 0 Feb 11 23:25 /dev/sda
brw-rw----. 1 root disk 8, 1 Feb 11 23:25 /dev/sda1
brw-rw----. 1 root disk 8, 2 Feb 11 23:25 /dev/sda2
brw-rw----. 1 root disk 8, 3 Feb 11 23:25 /dev/sda3
```

**Comment by javornikolov** [comment]
It's interesting what's up with the `newdisk` vagrant plugin. Can we see any output by it? It has some logging in it:
https://github.com/dbfit/vagrant-newdisk/blob/3e0ac06751427052548e2f4eafb4764cb9857552/lib/vagrant/newdisk/actions.rb#L23-L29

**Comment by MMatten** [comment]
It seems that there was some issue with an existing `disk1.vdi` file. If I delete it then things work properly again.

**Comment by MMatten** [comment]
I'll try to test this condition again.

**Comment by MMatten** [comment]
It seems that `vagrant destroy` doesn't destroy `disk1.vdi`. Is it possible to update the plugin to do this?

**Comment by javornikolov** [comment]
I think yes. There is another plugin https://github.com/kusnier/vagrant-persistent-storage where I can see some on-destroy hooks in `plugin.rb`.

**Comment by MMatten** [comment]
Do you think we should consider switching to this plugin?

**Comment by javornikolov** [comment]
I'm not sure since it's creating some file system too - I don't know  can it be turned off.

**Comment by MMatten** [comment]
Although the docs say that `vagrant destroy` doesn't destroy the risk with this plugin...

**Comment by MMatten** [comment]
> I think yes. There is another plugin https://github.com/kusnier/vagrant-persistent-storage where I can see some on-destroy hooks in plugin.rb.

I've not looked into creating vagrant plugins before. I'll have to read up on it. I don't think this issue is now blocking #543 though now.

**Comment by MMatten** [comment]
I'm now confused. My recent `vagrant destroy` execs do seem to destroy the disk image file. 

It's probably ok to close this issue I guess.

**Comment by MMatten** [comment]
And of course I've just reproduced it on my Ubuntu host...
