### ISSUE TITLE
CoreTests.CommonSuite.Symbols fails for PostgreSQL

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#557]
The INSERT into `testtbl` produces and exception:

```
org.postgresql.util.PSQLException: ERROR: column "val" is of type integer but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 44
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:410)
	at dbfit.fixture.StatementExecution.run(StatementExecution.java:13)
	at dbfit.fixture.DbObjectExecutionFixture.executeStatementAndEvaluateOutputs(DbObjectExecutionFixture.java:184)
	at dbfit.fixture.DbObjectExecutionFixture.runRow(DbObjectExecutionFixture.java:155)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:79)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

**Comment by MMatten** [comment]
![screenshot from 2017-03-18 11-00-02](https://cloud.githubusercontent.com/assets/1895701/24071465/37519726-0bca-11e7-94b7-84ff99b0672a.png)

I guess we can get PostgreSQL into the CI either via the option provided by Travis or via Docker.

**Comment by javornikolov** [comment]
> I guess we can get PostgreSQL into the CI either via the option provided by Travis or via Docker.

Absolutely! #558
