### ISSUE TITLE
Error building vagrant dev VM

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#568]
Fails with: -
```
==> default: Installing Cookbook Gems:
==> default: Compiling Cookbooks...
==> default: 
==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/git/libraries/z_provider_mapping.rb
==> default: ================================================================================
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: undefined method `set' for Chef::Platform:Class
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/git/libraries/z_provider_mapping.rb:6:in `<top (required)>'
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/git/libraries/z_provider_mapping.rb:
==> default: 
==> default:   1:  # provider mappings for Chef 11
==> default:   2:  
==> default:   3:  #########
==> default:   4:  # client
==> default:   5:  #########
==> default:   6>> Chef::Platform.set platform: :amazon, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:   7:  Chef::Platform.set platform: :centos, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:   8:  Chef::Platform.set platform: :debian, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:   9:  Chef::Platform.set platform: :fedora, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:  10:  Chef::Platform.set platform: :mac_os_x, resource: :git_client, provider: Chef::Provider::GitClient::Osx
==> default:  11:  Chef::Platform.set platform: :redhat, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:  12:  Chef::Platform.set platform: :scientific, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:  13:  Chef::Platform.set platform: :smartos, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:  14:  Chef::Platform.set platform: :solaris2, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default:  15:  Chef::Platform.set platform: :suse, resource: :git_client, provider: Chef::Provider::GitClient::Package
==> default: 
==> default: System Info:
==> default: ------------
==> default: chef_version=13.0.118
==> default: platform=centos
==> default: platform_version=7.3.1611
==> default: ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
==> default: program_name=chef-solo worker: ppid=4862;start=07:38:57;
==> default: executable=/opt/chef/bin/chef-solo
==> default: 
==> default: 
==> default: Running handlers:
==> default: [2017-04-22T07:39:05+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-04-22T07:39:05+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 08 seconds
==> default: [2017-04-22T07:39:05+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-04-22T07:39:05+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-04-22T07:39:05+00:00] ERROR: undefined method `set' for Chef::Platform:Class
==> default: [2017-04-22T07:39:05+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by MMatten** [comment]
Could be this issue causing it

https://github.com/chef-cookbooks/git/issues/119

**Comment by javornikolov** [comment]
Let's try to update cookbooks (`rm Berksfile.lock` and regenerate e.g. usign `berks install`)

**Comment by javornikolov** [comment]
For the mysql chef gem issue - maybe something like following will fix it:
``` diff
--- a/test_vm/vendor/cookbooks/dbfit_test/recipes/mysql.rb
+++ b/test_vm/vendor/cookbooks/dbfit_test/recipes/mysql.rb
@@ -2,7 +2,7 @@ include_recipe 'yum-mysql-community::mysql57'
 
 mysql2_chef_gem 'default' do
   gem_version '0.4.5'
-  client_version node['mysql']['version'] if node['mysql']
+  package_version node['mysql']['version'] if node['mysql']
   action :install
 end
```

**Comment by MMatten** [comment]
Now we see: -

```
==> default: [2017-04-22T13:09:26+00:00] INFO: service[mysql-default] enabled
==> default: 
==> default:         - enable service service[mysql-default]
==> default:       * service[mysql-default] action start
==> default: 
==> default:         
==> default:         ================================================================================
==> default:         Error executing action `start` on resource 'service[mysql-default]'
==> default:         ================================================================================
==> default:         
==> default:         Mixlib::ShellOut::ShellCommandFailed
==> default:         ------------------------------------
==> default:         Expected process to exit with [0], but received '1'
==> default:         ---- Begin output of /bin/systemctl --system start mysql-default ----
==> default:         STDOUT: 
==> default:         STDERR: Job for mysql-default.service failed because the control process exited with error code. See "systemctl status mysql-default.service" and "journalctl -xe" for details.
==> default:         ---- End output of /bin/systemctl --system start mysql-default ----
==> default:         Ran /bin/systemctl --system start mysql-default returned 1
==> default:         
==> default:         Resource Declaration:
==> default:         ---------------------
==> default:         # In /var/chef/cache/cookbooks/mysql/libraries/mysql_service_manager_systemd.rb
==> default:         
==> default:          81:       service mysql_name.to_s do
==> default:          82:         service_name mysql_name
==> default:          83:         provider Chef::Provider::Service::Systemd
==> default:          84:         supports restart: true, status: true
==> default:          85:         action [:enable, :start]
==> default:          86:       end
==> default:          87:     end
==> default:         
==> default:         Compiled Resource:
==> default:         ------------------
==> default:         # Declared in /var/chef/cache/cookbooks/mysql/libraries/mysql_service_manager_systemd.rb:81:in `block in <class:MysqlServiceManagerSystemd>'
==> default:         
==> default:         service("mysql-default") do
==> default:           provider Chef::Provider::Service::Systemd
==> default:           action [:enable, :start]
==> default:           updated true
==> default:           default_guard_interpreter :default
==> default:           service_name "mysql-default"
==> default:           enabled true
==> default:           running false
==> default:           masked false
==> default:           pattern "mysql-default"
==> default:           declared_type :service
==> default:           cookbook_name "dbfit_test"
==> default:           supports {:restart=>true, :status=>true}
==> default:         end
==> default:         
==> default: 
==> default:         System Info:
==> default:         ------------
==> default:         chef_version=13.0.118
==> default:         platform=centos
==> default:         platform_version=7.3.1611
==> default:         ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
==> default:         program_name=chef-solo worker: ppid=4816;start=13:00:44;
==> default:         executable=/opt/chef/bin/chef-solo
==> default:         
==> default: [2017-04-22T13:09:26+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:       
==> default:       ================================================================================
==> default:       Error executing action `start` on resource 'mysql_service_manager_systemd[default]'
==> default:       ================================================================================
==> default:       
==> default:       Mixlib::ShellOut::ShellCommandFailed
==> default:       ------------------------------------
==> default:       service[mysql-default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service_manager_systemd.rb line 81) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default:       ---- Begin output of /bin/systemctl --system start mysql-default ----
==> default:       STDOUT: 
==> default:       STDERR: Job for mysql-default.service failed because the control process exited with error code. See "systemctl status mysql-default.service" and "journalctl -xe" for details.
==> default:       ---- End output of /bin/systemctl --system start mysql-default ----
==> default:       Ran /bin/systemctl --system start mysql-default returned 1
==> default:       
==> default:       Resource Declaration:
==> default:       ---------------------
==> default:       # In /var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb
==> default:       
==> default:        50:           svc = mysql_service_manager(name, &block)
==> default:        51:         when 'sysvinit'
==> default:       
==> default:       Compiled Resource:
==> default:       ------------------
==> default:       # Declared in /var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb:50:in `svc_manager'
==> default:       
==> default:       mysql_service_manager_systemd("default") do
==> default:         action [:start]
==> default:         updated true
==> default:         updated_by_last_action true
==> default:         default_guard_interpreter :default
==> default:         declared_type :mysql_service_manager
==> default:         cookbook_name "dbfit_test"
==> default:         version "5.7"
==> default:         bind_address "127.0.0.1"
==> default:         initial_root_password "password"
==> default:         instance "default"
==> default:         socket "/var/run/mysql-default/mysqld.sock"
==> default:       end
==> default:       
==> default:       System Info:
==> default:       ------------
==> default:       chef_version=13.0.118
==> default:       platform=centos
==> default:       platform_version=7.3.1611
==> default:       ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
==> default:       program_name=chef-solo worker: ppid=4816;start=13:00:44;
==> default:       executable=/opt/chef/bin/chef-solo
==> default:       
==> default: [2017-04-22T13:09:26+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:     
==> default:     ================================================================================
==> default:     Error executing action `start` on resource 'mysql_service[default]'
==> default:     ================================================================================
==> default:     
==> default:     Mixlib::ShellOut::ShellCommandFailed
==> default:     ------------------------------------
==> default:     mysql_service_manager_systemd[default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb line 50) had an error: Mixlib::ShellOut::ShellCommandFailed: service[mysql-default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service_manager_systemd.rb line 81) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default:     ---- Begin output of /bin/systemctl --system start mysql-default ----
==> default:     STDOUT: 
==> default:     STDERR: Job for mysql-default.service failed because the control process exited with error code. See "systemctl status mysql-default.service" and "journalctl -xe" for details.
==> default:     ---- End output of /bin/systemctl --system start mysql-default ----
==> default:     Ran /bin/systemctl --system start mysql-default returned 1
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/dbfit_test/recipes/mysql.rb
==> default:     
==> default:      15: mysql_service 'default' do
==> default:      16:   version node['mysql']['version'] if node['mysql'] && node['mysql']['version']
==> default:      17:   bind_address mysql_connection_info[:host]
==> default:      18:   initial_root_password mysql_connection_info[:password]
==> default:      19:   action [:create, :start]
==> default:      20: end
==> default:      21: 
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/dbfit_test/recipes/mysql.rb:15:in `from_file'
==> default:     
==> default:     mysql_service("default") do
==> default:       action [:create, :start]
==> default:       updated true
==> default:       updated_by_last_action true
==> default:       default_guard_interpreter :default
==> default:       declared_type :mysql_service
==> default:       cookbook_name "dbfit_test"
==> default:       recipe_name "mysql"
==> default:       version "5.7"
==> default:       bind_address "127.0.0.1"
==> default:       initial_root_password "password"
==> default:     end
==> default:     
==> default:     System Info:
==> default:     ------------
==> default:     chef_version=13.0.118
==> default:     platform=centos
==> default:     platform_version=7.3.1611
==> default:     ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
==> default:     program_name=chef-solo worker: ppid=4816;start=13:00:44;
==> default:     executable=/opt/chef/bin/chef-solo
==> default:     
==> default: [2017-04-22T13:09:26+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2017-04-22T13:09:26+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-04-22T13:09:26+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 62 resources updated in 08 minutes 42 seconds
==> default: [2017-04-22T13:09:26+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-04-22T13:09:26+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-04-22T13:09:26+00:00] ERROR: mysql_service[default] (dbfit_test::mysql line 15) had an error: Mixlib::ShellOut::ShellCommandFailed: mysql_service_manager_systemd[default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb line 50) had an error: Mixlib::ShellOut::ShellCommandFailed: service[mysql-default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service_manager_systemd.rb line 81) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of /bin/systemctl --system start mysql-default ----
==> default: STDOUT: 
==> default: STDERR: Job for mysql-default.service failed because the control process exited with error code. See "systemctl status mysql-default.service" and "journalctl -xe" for details.
==> default: ---- End output of /bin/systemctl --system start mysql-default ----
==> default: Ran /bin/systemctl --system start mysql-default returned 1
==> default: [2017-04-22T13:09:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by javornikolov** [comment]
Any insights in the `journalctl -xe` output?

**Comment by MMatten** [comment]
Some more output: -
```
[vagrant@dbfitvm ~]$ sudo systemctl status mysql-default.service

● mysql-default.service - mysql_service[mysql-default]
   Loaded: loaded (/etc/systemd/system/mysql-default.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2017-04-22 13:59:23 UTC; 12min ago
  Process: 4780 ExecStartPost=/usr/libexec/mysql-default-wait-ready $MAINPID (code=exited, status=1/FAILURE)
  Process: 4779 ExecStart=/usr/sbin/mysqld --defaults-file=/etc/mysql-default/my.cnf --basedir=/usr (code=exited, status=1/FAILURE)
 Main PID: 4779 (code=exited, status=1/FAILURE)

Apr 22 13:59:21 dbfitvm systemd[1]: Starting mysql_service[mysql-default]...
Apr 22 13:59:22 dbfitvm systemd[1]: mysql-default.service: main process exited, code=exited, status=1/FAILURE
Apr 22 13:59:23 dbfitvm systemd[1]: mysql-default.service: control process exited, code=exited status=1
Apr 22 13:59:23 dbfitvm systemd[1]: Failed to start mysql_service[mysql-default].
Apr 22 13:59:23 dbfitvm systemd[1]: Unit mysql-default.service entered failed state.
Apr 22 13:59:23 dbfitvm systemd[1]: mysql-default.service failed.
```

**Comment by javornikolov** [comment]
There should be also mysql logs somewhere (maybe under `/var/log/mysql`).

**Comment by MMatten** [comment]
> Any insights in the journalctl -xe output?

I can't see anything obvious...

```
[vagrant@dbfitvm ~]$ sudo journalctl -xe

Apr 22 14:18:01 dbfitvm systemd[1]: Starting Session 7 of user vagrant.
-- Subject: Unit session-7.scope has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit session-7.scope has begun starting up.
Apr 22 14:18:26 dbfitvm sudo[4878]:  vagrant : TTY=pts/1 ; PWD=/home/vagrant ; USER=root ; COMMAND=/bin/journalctl -xe
Apr 22 14:19:19 dbfitvm sshd[4854]: Received disconnect from 10.0.2.2: 11: disconnected by user
Apr 22 14:19:19 dbfitvm sshd[4851]: pam_unix(sshd:session): session closed for user vagrant
Apr 22 14:19:19 dbfitvm systemd-logind[642]: Removed session 7.
-- Subject: Session 7 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID 7 has been terminated.
Apr 22 14:19:30 dbfitvm sshd[4884]: Accepted publickey for vagrant from 10.0.2.2 port 41868 ssh2: RSA 38:de:9f:fe:24:ed:7d:05:8c:b4:0d:b9:38:f1
Apr 22 14:19:30 dbfitvm systemd[1]: Started Session 8 of user vagrant.
-- Subject: Unit session-8.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit session-8.scope has finished starting up.
-- 
-- The start-up result is done.
Apr 22 14:19:30 dbfitvm sshd[4884]: pam_unix(sshd:session): session opened for user vagrant by (uid=0)
Apr 22 14:19:30 dbfitvm systemd-logind[642]: New session 8 of user vagrant.
-- Subject: A new session 8 has been created for user vagrant
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A new session with the ID 8 has been created for the user vagrant.
-- 
-- The leading process of the session is 4884.
Apr 22 14:19:30 dbfitvm systemd[1]: Starting Session 8 of user vagrant.
-- Subject: Unit session-8.scope has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit session-8.scope has begun starting up.
Apr 22 14:19:44 dbfitvm sudo[4911]:  vagrant : TTY=pts/1 ; PWD=/home/vagrant ; USER=root ; COMMAND=/bin/journalctl -xe
```

**Comment by MMatten** [comment]
> There should be also mysql logs somewhere (maybe under /var/log/mysql).

I can only see: -

`/var/log/mysql-default/error.log`

It contains recent entries to I think the service is running but I can't run the MySQL integration tests: -

```
* What went wrong:
Execution failed for task ':dbfit-java:mysql:integrationTest'.
> java.sql.SQLException: Access denied for user 'dbfit_user'@'localhost' (using password: YES)
```

as the provisioning hasn't finished.

**Comment by MMatten** [comment]
There is also `/var/log/mysql.log` but it's completely empty.

**Comment by MMatten** [comment]
I can try pegging back the `mysql` cookbook to a slightly earlier version.

**Comment by javornikolov** [comment]
The previous version was 8.2.0. In any case - we anyway have mysql covered in Travis CI build so we can skip it for the purpose of testing the other adapters.

**Comment by MMatten** [comment]
It seems that `SELinux` is preventing MySQL from starting up. It seems to be running in enforcing mode. Switch it, manually, to permissive mode allows MySQL to start up.

We're already trying to disable SELinux in our main recipe though.

**Comment by javornikolov** [comment]
> We're already trying to disable SELinux in our main recipe though.

Interesting... So maybe it the disabling either doesn't work or needs restart.

**Comment by javornikolov** [comment]
As per [selinux](https://github.com/chef-cookbooks/selinux) cookbook docs - disabling needs reboot. Maybe we should try permissive mode instead.

**Comment by MMatten** [comment]
I've just tried Permissive instead of Disabled. No luck. The service doesn't start. 

Do we need a new CentOS image? :(

**Comment by MMatten** [comment]
Maybe we can insert a manual disabling via `setenforce 0`.

**Comment by javornikolov** [comment]
Looking deeper at the docs - I think all modes may need restart. But there is another attribute called `temporary` which is supposed to work without reboot.

**Comment by javornikolov** [comment]
BTW - I'm not quite sure whether SELinux is coming with the box itself (it might be installed while satisfying the dependencies of `selinux` recipe - which we're using for no other reason to disable it :-))

**Comment by MMatten** [comment]
> BTW - I'm not quite sure whether SELinux is coming with the box itself (it might be installed while satisfying the dependencies of selinux recipe - which we're using for no other reason to disable it :-))

Ah, may be from an older image we were using at one point.
