### ISSUE TITLE
Cannot insert into table with Geometry column

### ISSUE THREAD

**Issue by lightpear** [dbfit/dbfit#585]
We're using DBFit on a PostGresql database that has PostGIS installed.

If I have a table of this schema:
```
Create table my_table(
    str TEXT,
   geom geometry(Polygon, 27700)
)
```

The following will fail:
```
!|insert| my_table|
|str|
|a string|
```

As you can see, I'm not even trying to insert into the geometry column. The mere existence of it causes DBFit to fail.

The full exception is:
```
java.lang.UnsupportedOperationException: Type USER-DEFINED is not supported
	at dbfit.environment.PostgresEnvironment.getSqlType(PostgresEnvironment.java:140)
	at dbfit.environment.PostgresEnvironment.readIntoParams(PostgresEnvironment.java:76)
	at dbfit.environment.PostgresEnvironment.getAllColumns(PostgresEnvironment.java:58)
	at dbfit.api.DbTable.(DbTable.java:24)
	at dbfit.fixture.Insert.getTargetDbObject(Insert.java:32)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:61)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

The only way to insert is to use an execute:
```|Execute | INSERT INTO my_table(str) VALUES ('a string')|```

**Comment by javornikolov** [comment]
Thanks for reporting that! DbFit is in general parsing all the columns (no matter used or not).

This is similar to #439. Maybe we can apply a similar fix.
