### ISSUE TITLE
NullPointerException when running query

### ISSUE THREAD

**Issue by sej2105** [dbfit/dbfit#601]
Hi,

I am trying to run the below test and get a Null Pointer Exception when running the query. 

This is the test I am running:
```

!define TEST_SYSTEM {fit}

!|dbfit.SqlServerTest|
!|Connect|jdbc:sqlserver://myhost;databaseName=Auto_DEVTEST;integratedSecurity=true;|


!|Query|select * from SecurityGroup|
|SecurityGroupID|
|14|
```
This the error i am receiving: 

`

Queryjava.lang.NullPointerException 	at dbfit.fixture.RowSetFixture.findMatchingRow(RowSetFixture.java:120) 	at dbfit.fixture.RowSetFixture.doRow(RowSetFixture.java:107) 	at fit.Fixture.doRows(Fixture.java:162) 	at fit.ColumnFixture.doRows(ColumnFixture.java:13) 	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:93) 	at fit.Fixture.doTable(Fixture.java:156) 	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21) 	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104) 	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89) 	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73) 	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27) 	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42) 	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26) 	at fit.Fixture.doTables(Fixture.java:81) 	at fit.FitServer.process(FitServer.java:81) 	at fit.FitServer.run(FitServer.java:56) 	at fit.FitServer.main(FitServer.java:41) | select * from SecurityGroup
-- | --
SecurityGroupIDCould not find field: SecurityGroupID.

`
This is my classPath: !path C:\Source\FitNesseTests.Fixtures\bin\Debug\dbfit-complete-3.2.0\lib\*

and these are the files in the lib folder:

> 
![image](https://user-images.githubusercontent.com/32062291/30653878-38d73c3a-9e24-11e7-98bd-763761cc137c.png)

Please could you help resolve or let me know if any files need to added/ updated. When running the test
like below: 
`!|Query|select * from SecurityGroup|`

I receive null pointer exceptions, 18 times, which is the correct number of records in the table. 

Has  anyone got any ideas on how to resolve or what could be causing this?

Many thanks

**Comment by vinuthagp** [comment]
Hi,

Were you able to solve this issue?

**Comment by MMatten** [comment]
Can you please show us the image of the test results?

Does the table "SecurityGroup" actually contain the column "SecurityGroupID"?
