### ISSUE TITLE
Vagant VM provisioning fails on latest CentOS box image

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#609]
In prep for #608.

Fails with:-

```
==> default:     ================================================================================
==> default:     Error executing action `create` on resource 'lvm_physical_volume[/dev/sdb]'
==> default:     ================================================================================
==> default:     
==> default:     LVM::External::ExternalFailure
==> default:     ------------------------------
==> default:     Fatal error, `/sbin/lvm pvcreate /dev/sdb ` returned 5 with 'Device /dev/sdb not found (or ignored by filtering).'
==> default:     
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_physical_volume.rb:51:in `action_create'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/dbfit_test/recipes/diskspace.rb
==> default:     
==> default:       1: lvm_physical_volume '/dev/sdb' do
==> default:       2:   action :create
==> default:       3: end
==> default:       4: 
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/dbfit_test/recipes/diskspace.rb:1:in `from_file'
==> default:     
==> default:     lvm_physical_volume("/dev/sdb") do
==> default:       provider Chef::Provider::LvmPhysicalVolume
==> default:       action [:create]
==> default:       default_guard_interpreter :default
==> default:       declared_type :lvm_physical_volume
==> default:       cookbook_name "dbfit_test"
==> default:       recipe_name "diskspace"
==> default:     end
==> default:     
==> default:     System Info:
==> default:     ------------
==> default:     chef_version=13.6.4
==> default:     platform=centos
==> default:     platform_version=7.4.1708
==> default:     ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
==> default:     program_name=chef-solo worker: ppid=29622;start=16:19:42;
==> default:     executable=/opt/chef/bin/chef-solo
==> default:     
==> default: [2017-11-25T16:21:08+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2017-11-25T16:21:08+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-11-25T16:21:08+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 8 resources updated in 01 minutes 26 seconds
==> default: [2017-11-25T16:21:08+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-11-25T16:21:08+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-11-25T16:21:08+00:00] ERROR: lvm_physical_volume[/dev/sdb] (dbfit_test::diskspace line 1) had an error: LVM::External::ExternalFailure: Fatal error, `/sbin/lvm pvcreate /dev/sdb ` returned 5 with 'Device /dev/sdb not found (or ignored by filtering).'
```

It looks like we have the following disks on the box:-

```
[root@dbfitvm ~]# fdisk -l

Disk /dev/sda: 42.9 GB, 42949672960 bytes, 83886080 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x000a22d6

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1            2048        4095        1024   83  Linux
/dev/sda2   *        4096     2101247     1048576   83  Linux
/dev/sda3         2101248    83886079    40892416   8e  Linux LVM

Disk /dev/mapper/VolGroup00-LogVol00: 40.2 GB, 40231763968 bytes, 78577664 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/VolGroup00-LogVol01: 1610 MB, 1610612736 bytes, 3145728 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

**Comment by MMatten** [comment]
Hmmm....this looks like it could be another case of a disk image hanging around from a previous VM...

**Comment by MMatten** [comment]
Cause was previous VM's `disk1.vdi` file not being destroyed.
