### ISSUE TITLE
Test VM creation error when creating Postgres DB

### ISSUE THREAD

**Issue by MMatten** [dbfit/dbfit#619]
The Return of the Brittle (Postgres recipe issues).

```
> default:   * postgresql_database[dbfit] action create
==> default: 
==> default:     
==> default:     ================================================================================
==> default:     Error executing action `create` on resource 'postgresql_database[dbfit]'
==> default:     ================================================================================
==> default:     
==> default:     NameError
==> default:     ---------
==> default:     uninitialized constant PGconn
==> default:     
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:132:in `db'
==> default:     /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:97:in `exists?'
==> default:     /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:46:in `block in <class:Postgresql>'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/dbfit_test/recipes/postgres.rb
==> default:     
==> default:      14: postgresql_database 'dbfit' do
==> default:      15:   connection postgresql_connection_info
==> default:      16:   action :create
==> default:      17: end
==> default:      18: 
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/dbfit_test/recipes/postgres.rb:14:in `from_file'
==> default:     
==> default:     postgresql_database("dbfit") do
==> default:       provider Chef::Provider::Database::Postgresql
==> default:       action [:create]
==> default:       default_guard_interpreter :default
==> default:       database_name "dbfit"
==> default:       declared_type :postgresql_database
==> default:       cookbook_name "dbfit_test"
==> default:       recipe_name "postgres"
==> default:       connection {:host=>"127.0.0.1", :port=>5432, :username=>"postgres", :password=>"postgres"}
==> default:     end
==> default:     
==> default:     System Info:
==> default:     ------------
==> default:     chef_version=13.7.16
==> default:     platform=centos
==> default:     platform_version=7.4.1708
==> default:     ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
==> default:     program_name=chef-solo worker: ppid=15115;start=23:35:22;
==> default:     executable=/opt/chef/bin/chef-solo
==> default:     
==> default: [2018-02-02T23:41:10+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2018-02-02T23:41:10+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2018-02-02T23:41:10+00:00] INFO: template[/etc/systemd/system/postgresql.service] sending reload action to service[postgresql] (delayed)
==> default: [2018-02-02T23:41:10+00:00] INFO: template[/etc/systemd/system/postgresql.service] sending reload action to service[postgresql] (delayed)
==> default: Recipe: postgresql::server_redhat
==> default:   * service[postgresql] action reload
==> default: [2018-02-02T23:41:10+00:00] INFO: service[postgresql] reloaded
==> default: [2018-02-02T23:41:10+00:00] INFO: service[postgresql] reloaded
==> default: 
==> default:     - reload service service[postgresql]
==> default: 
==> default: Running handlers:
==> default: [2018-02-02T23:41:10+00:00] ERROR: Running exception handlers
==> default: [2018-02-02T23:41:10+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2018-02-02T23:41:10+00:00] ERROR: Exception handlers complete
==> default: [2018-02-02T23:41:10+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 68 resources updated in 05 minutes 48 seconds
==> default: [2018-02-02T23:41:10+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2018-02-02T23:41:10+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2018-02-02T23:41:10+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2018-02-02T23:41:10+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2018-02-02T23:41:10+00:00] ERROR: postgresql_database[dbfit] (dbfit_test::postgres line 14) had an error: NameError: uninitialized constant PGconn
==> default: [2018-02-02T23:41:10+00:00] ERROR: postgresql_database[dbfit] (dbfit_test::postgres line 14) had an error: NameError: uninitialized constant PGconn
==> default: [2018-02-02T23:41:10+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
==> default: [2018-02-02T23:41:10+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by MMatten** [comment]
I've also tried this after zapping `Berksfile.lock` and I get the same result.

**Comment by MMatten** [comment]
More info: https://github.com/sous-chefs/postgresql/issues/480

**Comment by MMatten** [comment]
The manual workaround is to de-install the broken v1.0 and install v0.21 on the guest:-

`sudo /opt/chef/embedded/bin/gem uninstall pg`

`sudo yum install postgres-devel`

`sudo /opt/chef/embedded/bin/gem install pg -v 0.21`

**Comment by bhuesemann** [comment]
This can be automated be using brute force in postgres.rb
'''
# fix for https://github.com/dbfit/dbfit/issues/619; uninstall and install pg v 0.21
chef_gem 'pg' do
  action :remove
end

chef_gem 'pg' do
  version '0.21'
  action :install
end

postgresql_database 'dbfit' do
  connection postgresql_connection_info
  action :create
end
'''
