### ISSUE TITLE
Issue with Command line fixture in dbfit observed

### ISSUE THREAD

**Issue by nohoyuar** [dbfit/dbfit#623]
Hi,

I wanted to use command line arguments in dbfit by importing commandline fixture.
I did download a command line fixture from http://fit.c2.com/files/CommandLineFixture/CommandLineFixture.java and created a jar file using this .java and then placed it in the repositories of lib/*.jar 
I tried importing the jar file in dbfit page and tried running some syntax like below,

!path lib/*.jar

!| import fixture|
|dbfit.fixture|

!|CommandLineFixture|
|command|rm -rf test.txt|

and getting the below error message,
java.lang.NoClassDefFoundError: fit/CommandLineFixture (wrong name: fitnesse/fit/CommandLineFixture)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at fit.FixtureLoader.loadFixtureClass(FixtureLoader.java:67)
	at fit.FixtureLoader.instantiateFixture(FixtureLoader.java:60)
	at fit.FixtureLoader.instantiateFirstValidFixtureClass(FixtureLoader.java:84)
	at fit.FixtureLoader.disgraceThenLoad(FixtureLoader.java:44)
	at fit.Fixture.loadFixture(Fixture.java:141)
	at fit.Fixture.getLinkedFixtureWithArgs(Fixture.java:133)
	at fit.Fixture.interpretFollowingTables(Fixture.java:119)
	at fit.Fixture.interpretTables(Fixture.java:106)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)

Can you help me on this. 

Thanks & Regards,
Arun K

**Comment by MMatten** [comment]
Please post this question in the DbFit discussion forum.

https://groups.google.com/forum/#!forum/dbfit

As this isn't a DbFit-specific issue I'm going to close this one.

**Comment by MMatten** [comment]
You need to add the full class name including the package name part.

Sent from my iPhone

On 14 Mar 2018, at 10:53, nohoyuar <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I wanted to use command line arguments in dbfit by importing commandline fixture.
I did download a command line fixture from http://fit.c2.com/files/CommandLineFixture/CommandLineFixture.java and created a jar file using this .java and then placed it in the repositories of lib/*.jar
I tried importing the jar file in dbfit page and tried running some syntax like below,

!path lib/*.jar

!| import fixture|
|dbfit.fixture|

!|CommandLineFixture|
|command|rm -rf test.txt|

and getting the below error message,
java.lang.NoClassDefFoundError: fit/CommandLineFixture (wrong name: fitnesse/fit/CommandLineFixture)
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at fit.FixtureLoader.loadFixtureClass(FixtureLoader.java:67)
at fit.FixtureLoader.instantiateFixture(FixtureLoader.java:60)
at fit.FixtureLoader.instantiateFirstValidFixtureClass(FixtureLoader.java:84)
at fit.FixtureLoader.disgraceThenLoad(FixtureLoader.java:44)
at fit.Fixture.loadFixture(Fixture.java:141)
at fit.Fixture.getLinkedFixtureWithArgs(Fixture.java:133)
at fit.Fixture.interpretFollowingTables(Fixture.java:119)
at fit.Fixture.interpretTables(Fixture.java:106)
at fit.Fixture.doTables(Fixture.java:80)
at fit.FitServer.process(FitServer.java:81)
at fit.FitServer.run(FitServer.java:56)
at fit.FitServer.main(FitServer.java:41)

Can you help me on this.

Thanks & Regards,
Arun K
