### ISSUE TITLE
java.lang.UnsupportedOperationException: Type TINYINT UNSIGNED is not supported

### ISSUE THREAD

**Issue by xuguolong2017** [dbfit/dbfit#625]
CREATE TABLE tb_user
(
  id       INT AUTO_INCREMENT
    PRIMARY KEY,
  username VARCHAR(20)         NULL,
  password VARCHAR(20)         NULL,
  age      TINYINT(3) UNSIGNED NULL
);

Gauge Unsupported TINYINT UNSIGNED！

**Comment by MMatten** [comment]
At first glance this doesn’t look like a DbFit error. Make sure your database accepts this statement by using some other database client.

**Comment by xuguolong2017** [comment]
You can see the following excetion message and  you can test it.

<br/><table><tr><td>dbfit.MySqlTest</td></tr></table><br/><br/><table><tr><td>set option</td><td>debuglog</td><td>true</td></tr></table><br/><br/><table><tr><td>Connect</td><td>localhost:3306</td><td>root</td><td>123456</td><td>dbfit</td></tr></table><br/><br/><table><tr><td>set option</td><td>autocommit</td><td>false</td></tr></table><br/><br/><table><tr><td>query</td><td>select * from tb_user</td></tr><tr><td>username</td><td>password?</td><td class="error">age?<hr><pre><div class="fit_stacktrace">java.lang.UnsupportedOperationException: Type TINYINT UNSIGNED is not supported
        	at dbfit.environment.MySqlEnvironment.getJavaClass(MySqlEnvironment.java:171)
        	at dbfit.fixture.Query.getJavaClassForColumn(Query.java:69)
        	at dbfit.fixture.RowSetFixture.bind(RowSetFixture.java:79)
        	at fit.ColumnFixture.doRows(ColumnFixture.java:18)
        	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:93)
        	at fit.Fixture.doTable(Fixture.java:156)
        	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
        	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
        	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
        	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
        	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
        	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
        	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
        	at fit.GaugeFixture.doTables(GaugeFixture.java:25)
