### ISSUE TITLE
MySQL JSON data type not supported

### ISSUE THREAD

**Issue by arulece06** [dbfit/dbfit#633]
We are using MySQL 5.7 with JSON data type for stored proc argument.

While trying to test this with DBFit, I'm getting below exception.

java.lang.UnsupportedOperationException: Type JSON is not supported
	at dbfit.environment.MySqlEnvironment.getSqlType(MySqlEnvironment.java:143)
	at dbfit.environment.MySqlEnvironment.getAllProcedureParameters(MySqlEnvironment.java:211)
	at dbfit.api.DbStoredProcedure.getAllParams(DbStoredProcedure.java:57)
	at dbfit.api.DbStoredProcedure.findAccessorForParamWithName(DbStoredProcedure.java:49)
	at dbfit.api.DbStoredProcedure.getDbParameterAccessor(DbStoredProcedure.java:32)
	at dbfit.fixture.DbObjectExecutionFixture.getAccessors(DbObjectExecutionFixture.java:121)
	at dbfit.fixture.DbObjectExecutionFixture.getAccessors(DbObjectExecutionFixture.java:108)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:71)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)

**Comment by giuseppenicolais** [comment]
Has this been fixed in any release ? Thanks

**Comment by giuseppenicolais** [comment]
with my colleagues we found a workaround for this 
`select CAST(json_column AS CHAR(1000)) as json_column`
