### ISSUE TITLE
Null Pointer Exception w/ newer FitNesse versions

### ISSUE THREAD

**Issue by rckpyprsczrs** [dbfit/dbfit#635]
Is the 2015 version of FitNesse the only working version with DBFit 3.x?  It seems anything after 2015 causes null pointer exceptions.

java.lang.NullPointerException
	at dbfit.fixture.RowSetFixture.findMatchingRow(RowSetFixture.java:105)
	at dbfit.fixture.RowSetFixture.doRow(RowSetFixture.java:92)
	at fit.Fixture.doRows(Fixture.java:162)
	at fit.ColumnFixture.doRows(ColumnFixture.java:13)
	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:79)
	at fit.Fixture.doTable(Fixture.java:156)
	at fit.Fixture.interpretFollowingTables(Fixture.java:121)
	at fit.Fixture.interpretTables(Fixture.java:107)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)

or 

java.lang.NullPointerException
	at fit.ColumnFixture.doRows(ColumnFixture.java:12)
	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:79)
	at fit.Fixture.doTable(Fixture.java:156)
	at fit.Fixture.interpretFollowingTables(Fixture.java:121)
	at fit.Fixture.interpretTables(Fixture.java:107)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)

**Comment by MMatten** [comment]
This has probably been resolved in the codebase (we're using more recent Fitnesse versions) but we have yet to put out an updated release.

**Comment by vinuthagp** [comment]
Hi, Any solution to the null pointer exception?

**Comment by MMatten** [comment]
I believe there was a breaking change in the Fit API in a more recent version of FitNesse (and the DbFit project had to make changes to compensate for this). 

Things will be working again with the (imminent!) release of v4.0.0 of DbFit.

**Comment by vinuthagp** [comment]
Hi Matt,

Can you please provide me the older version so that I can run it for now?
