### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by krishabh85** [dbfit/dbfit#640]
I ran a Suite and it is giving results correctly but still when I see its Execution log, it is having some standard error, can anyone help me please.

Standard Error:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at fit.TypeAdapter$DelegateClassAdapter.parse(TypeAdapter.java:354)
	at dbfit.util.ParseHelper.parse(ParseHelper.java:71)
	at dbfit.fixture.RowSetFixture$CurrentDataRowTypeAdapter.parse(RowSetFixture.java:49)
	at fit.Fixture$CellComparator.parseCell(Fixture.java:395)
	at fit.Fixture$CellComparator.compareCellToResult(Fixture.java:375)
	at fit.Fixture$CellComparator.access$100(Fixture.java:360)
	at fit.Fixture.compareCellToResult(Fixture.java:302)
	at fit.Fixture.check(Fixture.java:298)
	at fit.ColumnFixture.check(ColumnFixture.java:54)
	at fit.Binding$QueryBinding.doCell(Binding.java:218)
	at dbfit.util.SymbolAccessQueryBinding.doCell(SymbolAccessQueryBinding.java:38)
	at fit.ColumnFixture.doCell(ColumnFixture.java:40)
	at fit.Fixture.doCells(Fixture.java:174)
	at fit.Fixture.doRow(Fixture.java:168)
	at fit.ColumnFixture.doRow(ColumnFixture.java:27)
	at dbfit.fixture.RowSetFixture.doRow(RowSetFixture.java:109)
	at fit.Fixture.doRows(Fixture.java:162)
	at fit.ColumnFixture.doRows(ColumnFixture.java:19)
	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:93)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
Caused by: java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:470)
	at java.math.BigDecimal.<init>(BigDecimal.java:739)
	at dbfit.util.BigDecimalParseDelegate.parse(BigDecimalParseDelegate.java:7)
	... 35 more
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at fit.TypeAdapter$DelegateClassAdapter.parse(TypeAdapter.java:354)
	at dbfit.util.ParseHelper.parse(ParseHelper.java:71)
	at dbfit.fixture.RowSetFixture$CurrentDataRowTypeAdapter.parse(RowSetFixture.java:49)
	at fit.Fixture$CellComparator.parseCell(Fixture.java:395)
	at fit.Fixture$CellComparator.compareCellToResult(Fixture.java:375)
	at fit.Fixture$CellComparator.access$100(Fixture.java:360)
	at fit.Fixture.compareCellToResult(Fixture.java:302)
	at fit.Fixture.check(Fixture.java:298)
	at fit.ColumnFixture.check(ColumnFixture.java:54)
	at fit.Binding$QueryBinding.doCell(Binding.java:218)
	at dbfit.util.SymbolAccessQueryBinding.doCell(SymbolAccessQueryBinding.java:38)
	at fit.ColumnFixture.doCell(ColumnFixture.java:40)
	at fit.Fixture.doCells(Fixture.java:174)
	at fit.Fixture.doRow(Fixture.java:168)
	at fit.ColumnFixture.doRow(ColumnFixture.java:27)
	at dbfit.fixture.RowSetFixture.doRow(RowSetFixture.java:109)
	at fit.Fixture.doRows(Fixture.java:162)
	at fit.ColumnFixture.doRows(ColumnFixture.java:19)
	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:93)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
Caused by: java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:470)
	at java.math.BigDecimal.<init>(BigDecimal.java:739)
	at dbfit.util.BigDecimalParseDelegate.parse(BigDecimalParseDelegate.java:7)
	... 35 more

**Comment by MMatten** [comment]
Please transfer this request to the public support forum area where it will be better supported:-

https://groups.google.com/forum/#!forum/dbfit

Please post screen images there to help diagnose your issue.

Thanks.
