### ISSUE TITLE
DB Fit Oracle DB Connection

### ISSUE THREAD

**Issue by vinayak115** [dbfit/dbfit#666]
I have the below Test Script

!path lib\*.jar

|import fixture|
|dbfit.fixture|

!|DatabaseEnvironment|oracle|

|ConnectUsingFile|TestDbConnectionDbFitOracle.properties|

And I get the following error message:

java.lang.Error: java.lang.reflect.InvocationTargetException

                at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.createEnvironmentInstance(DbEnvironmentFactory.java:68)

                at dbfit.api.DbEnvironmentFactory.createEnvironmentInstance(DbEnvironmentFactory.java:102)

                at dbfit.api.DbEnvironmentFactory.newEnvironmentInstance(DbEnvironmentFactory.java:106)

                at dbfit.fixture.DatabaseEnvironment.setDatabaseEnvironment(DatabaseEnvironment.java:27)

                at dbfit.fixture.DatabaseEnvironment.doTable(DatabaseEnvironment.java:20)

                at fit.Fixture.interpretFollowingTables(Fixture.java:121)

                at fit.Fixture.interpretTables(Fixture.java:107)

                at fit.Fixture.doTables(Fixture.java:81)

                at fit.FitServer.process(FitServer.java:81)

                at fit.FitServer.run(FitServer.java:56)

                at fit.FitServer.main(FitServer.java:41)

Caused by: java.lang.reflect.InvocationTargetException

                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

                at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

                at java.lang.reflect.Constructor.newInstance(Unknown Source)

                at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.createEnvironmentInstance(DbEnvironmentFactory.java:65)

                ... 10 more

Caused by: java.lang.Error: Cannot initialise oracle rowset

                at dbfit.environment.OracleEnvironment.(OracleEnvironment.java:236)

                ... 15 more

Caused by: java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleResultSetImpl

                at java.net.URLClassLoader.findClass(Unknown Source)

                at java.lang.ClassLoader.loadClass(Unknown Source)

                at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)

                at java.lang.ClassLoader.loadClass(Unknown Source)

                at java.lang.Class.forName0(Native Method)

                at java.lang.Class.forName(Unknown Source)

                at dbfit.environment.OracleEnvironment.(OracleEnvironment.java:232)

                ... 15 more

**Comment by vinayak115** [comment]
Any pointers will be truly appreciated. I actually ojdbc8.jar connection and I invoke that library in the startFitness.bat

**Comment by javornikolov** [comment]
Which version is your jdbc driver? Could you try with 11.2

**Comment by javornikolov** [comment]
Also I do not see a slash in path:

!path lib/*.jar

**Comment by vinayak115** [comment]
Sorry, I'm new to this. When I execute java -jar ojdbc8.jar, I get the following details:
Oracle: 18.3 JDBC 4.2 compiled with Javac 1.8.0_171

**Comment by vinayak115** [comment]
Also, I updated the path. I still see the same error

**Comment by vinayak115** [comment]
Thank you! That worked

**Comment by javornikolov** [comment]
Yes, I believe we may close it. There is a workaround with the released version and we have merged a fix of compatibility with newer drivers in master branch.
