### ISSUE TITLE
Getting error to connect to Oracle database through DbFit client

### ISSUE THREAD

**Issue by rajops01** [dbfit/dbfit#669]
I am trying to connect to Oracle database through DbFit client with the following simple test:

**!path lib\*.jar
!|dbfit.OracleTest|
!|Connect|<Host Name>:<Port>/<Database Name>|<Username>|<Password>|**
 
But, getting below mentioned error when I run the test:

**"Could not complete testing: java.lang.Exception: FitClient: external process terminated before a connection could be established."**

When clicked on "Show Errors", below mentioned error is displayed
**"Exception in thread "main" java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at fit.FitServer.establishConnection(FitServer.java:150)
	at fit.FitServer.establishConnection(FitServer.java:146)
	at fit.FitServer.run(FitServer.java:54)
	at fit.FitServer.main(FitServer.java:41)"**

Could someone please assist asap on where it's going wrong? Thanks.

**Comment by javornikolov** [comment]
The connect URL need to be a valid for Oracle database (`:/` doesn't seem valid to me - it should match your database)
Also please try adding blank line between the different commands.
Consider adding a slash on !pah instruction - either lib/*.jar or lib\*.jar
