### ISSUE TITLE
Support for executing Oracle PL/SQL with Record Type parameter/return value

### ISSUE THREAD

**Issue by anaclcastro** [dbfit/dbfit#95]
Imagine I have a table:
CREATE TABLE departments (
  department_id     INTEGER,
  name                  VARCHAR2(20) );

INSERT INTO departments values (1, 'Computer Science');

Then, I have the function I want to test:
FUNCTION get_department_name (pct_department_id   IN departments.id%TYPE)
    RETURN departments.name%TYPE;

I define the test as:
!|execute procedure| get_department_name|
|pct_department_id|?|
|1|Computer Science|

Executing this test I get an exception: Type PL/SQL is not supported. I guess that this error is due to the Oracle JDBC drivers not supporting element types.Therefore, I was wondering if it is possible to implement a work around on dbfit to deal with these situations.

At a first glance, I was thinking on wrapping/casting these types into Strings. What type of drawbacks does this approach have? Are there better ways of doing this?

**Comment by forceedge01** [comment]
Having a similar issue, can this be resolved from the test level or do we have to change the production code?

```
java.lang.UnsupportedOperationException: Type PL/SQL RECORD is not supported
	at dbfit.environment.OracleEnvironment.getSqlType(OracleEnvironment.java:442)
	at dbfit.environment.OracleEnvironment.makeSingleParam(OracleEnvironment.java:347)
	at dbfit.environment.OracleEnvironment.makeSingleParam(OracleEnvironment.java:330)
	at dbfit.environment.OracleEnvironment.addSingleParam(OracleEnvironment.java:320)
	at dbfit.environment.OracleEnvironment.readIntoParams(OracleEnvironment.java:364)
	at dbfit.environment.OracleEnvironment.readIntoParams(OracleEnvironment.java:373)
	at dbfit.environment.OracleEnvironment.getAllProcedureParameters(OracleEnvironment.java:309)
	at dbfit.fixture.Inspect.inspectProcedure(Inspect.java:68)
	at dbfit.fixture.Inspect.doTable(Inspect.java:43)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```
